export const MOSTRAR_ALERTA = 'mOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';

export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_EXITOSO';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';

